export const KNOWLEDGE_DATA = {
  topic: {
    id: "codex-roadmap",
    title: "Codex 学习路线图",
    description: "由 AI 根据你的词条生成",
    chips: ["Codex", "CLI", "API", "Agent", "工作流", "入门", "实战", "自动化", "模型对比", "错误排查"],
    route: ["basics", "cli", "api", "cases"],
  },
  components: [
    { id: "basics", name: "基础概念", color: "#E8F7F4", line: "#83C9A8", x: 238, y: 166, weight: 84, locked: false, excluded: false, desc: "理解 Codex 的定位、适合场景、任务边界和常见使用方式。" },
    { id: "cli", name: "CLI 使用", color: "#EAF2FF", line: "#83D6EF", x: 410, y: 178, weight: 88, locked: false, excluded: false, desc: "掌握命令行启动、上下文读取、补丁修改、测试验证和分支协作。" },
    { id: "api", name: "API 接入", color: "#F1EDFF", line: "#8B7CF6", x: 446, y: 318, weight: 92, locked: false, excluded: false, desc: "学习如何把模型、工具调用和自动化脚本接入真实工作流。" },
    { id: "agent", name: "Agent 工作流", color: "#FFF3D8", line: "#F2C36B", x: 390, y: 454, weight: 90, locked: false, excluded: false, desc: "把计划、工具、验证、记忆和反馈组合成可控的 Agent 流程。" },
    { id: "cases", name: "实战案例", color: "#FFEDEC", line: "#FF7A7A", x: 250, y: 460, weight: 76, locked: false, excluded: false, desc: "用真实项目拆解 Codex 如何完成前端、文档、数据和自动化任务。" },
    { id: "models", name: "模型对比", color: "#EEF8EA", line: "#83C9A8", x: 164, y: 324, weight: 62, locked: false, excluded: false, desc: "对比 Codex、Claude、ChatGPT 在代码理解、推理和协作中的差异。" },
    { id: "automation", name: "自动化脚本", color: "#EDF7FF", line: "#69BFE7", x: 174, y: 214, weight: 71, locked: false, excluded: false, desc: "用脚本、定时任务和本地工具把重复工作自动化。" },
    { id: "advanced", name: "进阶路线", color: "#F8EEF9", line: "#C28AD8", x: 318, y: 104, weight: 68, locked: false, excluded: false, desc: "面向复杂项目的上下文工程、多代理协同和质量控制方法。" },
  ],
  videos: [
    { id: "v1", title: "新手如何开始学 Codex", creator: "AI 工具观察", duration: "06:24", componentId: "basics", tags: ["Codex", "入门"], summary: "用三个真实任务解释 Codex 的工作边界和最佳入门姿势。", reason: "它能帮用户建立正确预期，适合作为整张画布的第一步。", progress: 100, watched: true, coverType: "a", source: true },
    { id: "v2", title: "Codex 和普通代码助手有什么不同", creator: "产品实验室", duration: "07:18", componentId: "basics", tags: ["Codex", "Agent"], summary: "对比补全、聊天和可执行编码 Agent 的差别。", reason: "能快速理解为什么画布要围绕任务和组件组织。", progress: 46, watched: false, coverType: "b" },
    { id: "v3", title: "如何写好任务描述", creator: "效率研究所", duration: "05:42", componentId: "basics", tags: ["入门", "工作流"], summary: "拆解清晰目标、验收标准和上下文材料的写法。", reason: "任务描述会直接影响 Agent 的执行质量。", progress: 0, watched: false, coverType: "c" },
    { id: "v4", title: "从入门到部署的学习节奏", creator: "Dev 笔记", duration: "09:20", componentId: "basics", tags: ["路线", "实战"], summary: "把学习路线分成理解、练习、验证和发布四个阶段。", reason: "适合帮助用户规划后续学习顺序。", progress: 0, watched: false, coverType: "d" },
    { id: "v5", title: "Codex CLI 快速上手", creator: "命令行学院", duration: "08:06", componentId: "cli", tags: ["CLI", "Codex"], summary: "演示如何启动、读取项目、修改文件并运行验证命令。", reason: "它是 CLI 使用组件下最适合继续看的基础视频。", progress: 100, watched: true, coverType: "e" },
    { id: "v6", title: "用终端把任务跑完整", creator: "工程效率派", duration: "10:11", componentId: "cli", tags: ["CLI", "工作流"], summary: "围绕搜索、编辑、测试、总结四步展示完整编码循环。", reason: "能把零散命令串成可复用流程。", progress: 22, watched: false, coverType: "f" },
    { id: "v7", title: "本地项目上下文怎么给", creator: "AI 编程日课", duration: "04:55", componentId: "cli", tags: ["CLI", "上下文"], summary: "说明 README、截图、错误日志和测试输出如何帮助 Agent 判断。", reason: "可减少来回解释，让画布学习更快进入实践。", progress: 0, watched: false, coverType: "g" },
    { id: "v8", title: "常见 CLI 错误排查", creator: "Debug 小组", duration: "06:40", componentId: "cli", tags: ["错误排查", "CLI"], summary: "覆盖权限、路径、依赖和编码问题的排查路径。", reason: "它能降低新手使用门槛。", progress: 0, watched: false, coverType: "h" },
    { id: "v9", title: "API 自动化实战", creator: "AI 工具观察", duration: "08:32", componentId: "api", tags: ["API", "自动化"], summary: "用 API 把知识库整理、摘要和更新串成自动化流程。", reason: "它是 API 接入组件下最适合新手继续看的实战视频。", progress: 38, watched: false, coverType: "i", next: true },
    { id: "v10", title: "从视频提取关键词到画布", creator: "增长工程师", duration: "07:42", componentId: "api", tags: ["API", "视频"], summary: "模拟视频解析、关键词抽取和组件生成的数据流。", reason: "与本 Demo 的核心闭环高度相关。", progress: 0, watched: false, coverType: "j" },
    { id: "v11", title: "流式输出和工具调用", creator: "接口实践课", duration: "09:16", componentId: "api", tags: ["API", "Agent"], summary: "解释流式响应、工具调用和状态回写如何协同。", reason: "能帮助理解真实接入时的交互体验。", progress: 0, watched: false, coverType: "k" },
    { id: "v12", title: "API 成本与缓存策略", creator: "架构备忘录", duration: "06:58", componentId: "api", tags: ["API", "成本"], summary: "用缓存、批处理和降级策略控制推理成本。", reason: "接入真实服务前需要理解成本边界。", progress: 0, watched: false, coverType: "l" },
    { id: "v13", title: "Agent 工作流搭建", creator: "自动化研究员", duration: "11:03", componentId: "agent", tags: ["Agent", "工作流"], summary: "从计划、工具、执行、检查四个环节搭建 Agent 工作流。", reason: "它是 API 后的自然下一步。", progress: 0, watched: false, coverType: "m" },
    { id: "v14", title: "让 Agent 管理你的画布", creator: "产品实验室", duration: "06:19", componentId: "agent", tags: ["Agent", "画布"], summary: "展示 Agent 如何新增组件、移除重复视频和生成学习路线。", reason: "直接体现本产品的管理能力。", progress: 0, watched: false, coverType: "n" },
    { id: "v15", title: "任务拆解与验证清单", creator: "工程效率派", duration: "08:45", componentId: "agent", tags: ["Agent", "验证"], summary: "把大任务拆成可验证步骤，降低 Agent 走偏概率。", reason: "能提高复杂工作流的稳定性。", progress: 0, watched: false, coverType: "o" },
    { id: "v16", title: "多工具协作的边界", creator: "AI 编程日课", duration: "05:28", componentId: "agent", tags: ["Agent", "工具"], summary: "解释浏览器、文件、终端和外部系统如何分工。", reason: "帮助用户理解 Agent 不是聊天窗口，而是执行系统。", progress: 0, watched: false, coverType: "p" },
    { id: "v17", title: "三小时做一个可演示 Demo", creator: "路演工坊", duration: "12:10", componentId: "cases", tags: ["实战", "路演"], summary: "从范围收敛、样本数据、交互闭环到验收演示完整拆解。", reason: "适合路演前快速建立可体验原型。", progress: 0, watched: false, coverType: "q" },
    { id: "v18", title: "知识画布产品案例拆解", creator: "产品实验室", duration: "09:44", componentId: "cases", tags: ["实战", "画布"], summary: "分析为什么组件节点比视频列表更适合学习型内容。", reason: "能证明当前产品形态的价值。", progress: 0, watched: false, coverType: "r" },
    { id: "v19", title: "从收藏夹到学习路线", creator: "增长工程师", duration: "07:05", componentId: "cases", tags: ["实战", "路线"], summary: "把碎片收藏重构为可执行路线的产品方法。", reason: "说明保存画布和路线管理的必要性。", progress: 0, watched: false, coverType: "s" },
    { id: "v20", title: "移动端画布交互怎么做", creator: "UI 工程师 Leo", duration: "06:36", componentId: "cases", tags: ["移动端", "画布"], summary: "介绍缩放、拖动、抽屉和固定工具栏的移动端设计。", reason: "与当前 Demo 的体验设计直接相关。", progress: 0, watched: false, coverType: "t" },
    { id: "v21", title: "Claude 和 ChatGPT 对比", creator: "模型观察站", duration: "08:17", componentId: "models", tags: ["模型对比", "Claude"], summary: "从上下文、代码、写作和安全边界比较主流模型。", reason: "适合建立横向理解。", progress: 0, watched: false, coverType: "u" },
    { id: "v22", title: "Codex 适合哪些代码任务", creator: "Dev 笔记", duration: "05:51", componentId: "models", tags: ["模型对比", "Codex"], summary: "用前端、后端、测试和文档任务比较 Codex 的适用性。", reason: "帮助用户决定什么时候使用 Codex。", progress: 0, watched: false, coverType: "v" },
    { id: "v23", title: "代码 Agent 的评测方式", creator: "模型观察站", duration: "10:02", componentId: "models", tags: ["模型对比", "评测"], summary: "介绍通过任务完成率、回归测试和人工审查评估 Agent。", reason: "有助于建立理性预期。", progress: 0, watched: false, coverType: "w" },
    { id: "v24", title: "不同模型的协作分工", creator: "AI 工具观察", duration: "06:12", componentId: "models", tags: ["模型对比", "工作流"], summary: "让不同模型承担搜索、编码、总结和审阅角色。", reason: "为进阶多模型工作流打基础。", progress: 0, watched: false, coverType: "x" },
    { id: "v25", title: "用脚本自动整理素材", creator: "自动化研究员", duration: "07:37", componentId: "automation", tags: ["自动化", "脚本"], summary: "用本地脚本归档视频信息、标签和摘要。", reason: "它能把手动收藏变成持续更新的知识库。", progress: 0, watched: false, coverType: "y" },
    { id: "v26", title: "定时检查与提醒", creator: "效率研究所", duration: "05:34", componentId: "automation", tags: ["自动化", "提醒"], summary: "讲解如何周期性检查新视频并推送学习建议。", reason: "适合扩展后续的持续生长能力。", progress: 0, watched: false, coverType: "z" },
    { id: "v27", title: "自动生成学习周报", creator: "增长工程师", duration: "06:28", componentId: "automation", tags: ["自动化", "周报"], summary: "把观看记录、组件进度和下一步建议整理成周报。", reason: "能体现个人知识收藏夹的长期价值。", progress: 0, watched: false, coverType: "aa" },
    { id: "v28", title: "错误日志自动归因", creator: "Debug 小组", duration: "08:09", componentId: "automation", tags: ["自动化", "错误排查"], summary: "用日志和上下文让 Agent 给出可验证的排查建议。", reason: "把错误排查和自动化脚本连接起来。", progress: 0, watched: false, coverType: "ab" },
    { id: "v29", title: "进阶课程：如何通过 API 自动化你的知识库工作流", creator: "Claude_Master", duration: "03:20", componentId: "advanced", tags: ["Claude", "API", "自动化", "Agent", "工作流"], summary: "把 API、Agent 和知识库自动化组合成一条进阶实践路径。", reason: "它可以作为从视频页提取关键词生成画布的来源视频。", progress: 45, watched: false, coverType: "ac" },
    { id: "v30", title: "复杂项目的上下文工程", creator: "架构备忘录", duration: "11:49", componentId: "advanced", tags: ["进阶", "上下文"], summary: "讲解如何为大型项目组织上下文、规范和验证资料。", reason: "适合已掌握基础流程的用户继续深入。", progress: 0, watched: false, coverType: "ad" },
    { id: "v31", title: "多 Agent 协同实验", creator: "自动化研究员", duration: "09:26", componentId: "advanced", tags: ["进阶", "Agent"], summary: "用多个角色协同完成设计、编码、审阅和发布。", reason: "展示知识网络后续可以延展的方向。", progress: 0, watched: false, coverType: "ae" },
    { id: "v32", title: "质量控制与回归验证", creator: "工程效率派", duration: "07:14", componentId: "advanced", tags: ["进阶", "验证"], summary: "用测试、截图和人工审阅确保 Agent 修改可靠。", reason: "为真实生产接入提供质量保障。", progress: 0, watched: false, coverType: "af" },
    { id: "v33", title: "Prompt 到任务单的转换", creator: "AI 编程日课", duration: "04:45", componentId: "basics", tags: ["Prompt", "入门"], summary: "把一句需求拆成目标、输入、约束和验收清单。", reason: "帮助新手把想法转成 Agent 可执行任务。", progress: 0, watched: false, coverType: "ag" },
    { id: "v34", title: "CLI 与浏览器联调", creator: "UI 工程师 Leo", duration: "08:50", componentId: "cli", tags: ["CLI", "浏览器"], summary: "展示本地服务、浏览器截图和视觉 QA 的联调流程。", reason: "适合前端 Demo 开发场景。", progress: 0, watched: false, coverType: "ah" },
    { id: "v35", title: "Webhook 触发知识更新", creator: "接口实践课", duration: "06:53", componentId: "api", tags: ["API", "Webhook"], summary: "用 Webhook 把新视频、收藏和观看事件同步到画布。", reason: "为接入真实视频平台预留思路。", progress: 0, watched: false, coverType: "ai" },
    { id: "v36", title: "Agent 如何删除重复视频", creator: "产品实验室", duration: "05:47", componentId: "agent", tags: ["Agent", "去重"], summary: "用标题、摘要、标签和观看行为判断重复内容。", reason: "对应画布助手里的结构化建议。", progress: 0, watched: false, coverType: "aj" },
    { id: "v37", title: "路线卡片怎么设计", creator: "UI 工程师 Leo", duration: "06:07", componentId: "cases", tags: ["路线", "移动端"], summary: "讲解路线高亮、当前节点和下一步按钮的移动端呈现。", reason: "提升路线生成状态的表达。", progress: 0, watched: false, coverType: "ak" },
    { id: "v38", title: "模型选择的五个判断", creator: "模型观察站", duration: "07:31", componentId: "models", tags: ["模型对比", "选择"], summary: "从能力、速度、成本、上下文和工具生态选择模型。", reason: "帮助用户理解不同模型的定位。", progress: 0, watched: false, coverType: "al" },
    { id: "v39", title: "自动化脚本安全边界", creator: "Debug 小组", duration: "06:59", componentId: "automation", tags: ["自动化", "安全"], summary: "说明脚本权限、删除操作和外部接口调用的防护方法。", reason: "避免自动化带来不可控风险。", progress: 0, watched: false, coverType: "am" },
    { id: "v40", title: "从个人画布到团队知识库", creator: "架构备忘录", duration: "10:38", componentId: "advanced", tags: ["进阶", "知识库"], summary: "探索个人学习画布如何演化成团队协作知识网络。", reason: "为后续产品演进提供想象空间。", progress: 0, watched: false, coverType: "an" },
  ],
  savedCanvases: [
    { id: "codex-roadmap", title: "Codex 学习路线图", tags: ["Codex", "Agent"], videos: 42, progress: 28, updated: "今天 22:40" },
    { id: "claude-api", title: "Claude API 入门", tags: ["Claude", "API"], videos: 31, progress: 46, updated: "昨天 18:12" },
    { id: "agent-workflow", title: "Agent 工作流", tags: ["Agent", "自动化"], videos: 26, progress: 12, updated: "5 月 20 日" },
  ],
}

export default KNOWLEDGE_DATA
